### PR TITLE
Add NTP server

### PR DESCRIPTION
**Pull request by viandoxdev**
Adds a (local, not accurate) ntp server to the donkeycar manager docker compose, and make the cars sync to it.

### CODE REVIEW

**Comment by viandoxdev** [comment]
Ok, Just need testing on an actual car and this should be ready to merge

**Comment by Benvii** [comment]
Thanks I will test it tomorrow 👍

**Comment by Benvii** [comment]
Tested, doesn't work : 

Timedate ctl : 
```
(venv) pi@dababycar:~ $ timedatectl show
Timezone=Europe/London
LocalRTC=no
CanNTP=yes
NTP=no
NTPSynchronized=no
TimeUSec=Thu 2021-12-02 03:25:10 GMT
```
Journalctl : 
```
(venv) pi@dababycar:~ $ sudo journalctl -u donkey-ntp.service 
-- Logs begin at Thu 2021-12-02 02:32:29 GMT, end at Thu 2021-12-02 03:26:00 GMT. --
Dec 02 02:33:06 dababycar systemd[1]: Started donkey-ntp.service.
Dec 02 02:33:08 dababycar root[652]: Got donkeycar manager ip: 192.168.20.107
```

Config : 
```
(venv) pi@dababycar:~ $ cat /etc/systemd/timesyncd.conf
[Time]
NTP=192.168.20.107:123
```

Ntp service status, it seems that the NTP service try to use the wrong ntp server :  
```
(venv) pi@dababycar:~ $ sudo systemctl status ntp
● ntp.service - Network Time Service
   Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2021-12-02 02:33:08 GMT; 57min ago
     Docs: man:ntpd(8)
 Main PID: 646 (code=exited, status=0/SUCCESS)

Dec 02 02:33:07 dababycar ntpd[646]: Listen normally on 4 lo [::1]:123
Dec 02 02:33:07 dababycar ntpd[646]: Listen normally on 5 wlan0 [fe80::a4d0:69d8:ffc1:b070%3]:123
Dec 02 02:33:07 dababycar ntpd[646]: Listening on routing socket on fd #22 for interface updates
Dec 02 02:33:07 dababycar ntpd[646]: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
Dec 02 02:33:07 dababycar ntpd[646]: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
Dec 02 02:33:08 dababycar ntpd[646]: Soliciting pool server 51.195.120.107
Dec 02 02:33:08 dababycar ntpd[646]: ntpd exiting on signal 15 (Terminated)
Dec 02 02:33:08 dababycar systemd[1]: Stopping Network Time Service...
Dec 02 02:33:08 dababycar systemd[1]: ntp.service: Succeeded.
Dec 02 02:33:08 dababycar systemd[1]: Stopped Network Time Service.
```

Restarting NTP service works but still use the wrong NTP server : 
```
(venv) pi@dababycar:~ $ sudo systemctl status ntp
● ntp.service - Network Time Service
   Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-12-02 03:31:57 GMT; 1s ago
     Docs: man:ntpd(8)
  Process: 1307 ExecStart=/usr/lib/ntp/ntp-systemd-wrapper (code=exited, status=0/SUCCESS)
 Main PID: 1313 (ntpd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/ntp.service
           └─1313 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 109:115

Dec 02 03:31:57 dababycar ntpd[1313]: Listen and drop on 0 v6wildcard [::]:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listen normally on 2 lo 127.0.0.1:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listen normally on 3 wlan0 192.168.20.100:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listen normally on 4 lo [::1]:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listen normally on 5 wlan0 [fe80::a4d0:69d8:ffc1:b070%3]:123
Dec 02 03:31:57 dababycar ntpd[1313]: Listening on routing socket on fd #22 for interface updates
Dec 02 03:31:57 dababycar ntpd[1313]: kernel reports TIME_ERROR: 0x4041: Clock Unsynchronized
Dec 02 03:31:57 dababycar ntpd[1313]: kernel reports TIME_ERROR: 0x4041: Clock Unsynchronized
Dec 02 03:31:58 dababycar ntpd[1313]: Soliciting pool server 80.74.64.2

```

**Comment by Benvii** [comment]
Seems to work when removing those packages : `sudo apt remove ntp ntpdate`  I assume they are causing some kind of conflict.

After I have  : 
```
(venv) pi@dababycar:~ $ sudo systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: active (running) since Sun 2022-06-19 10:32:44 BST; 4s ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 1586 (systemd-timesyn)
   Status: "Idle."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/systemd-timesyncd.service
           └─1586 /lib/systemd/systemd-timesyncd

Jun 19 10:32:44 dababycar systemd[1]: Starting Network Time Synchronization...
Jun 19 10:32:44 dababycar systemd[1]: Started Network Time Synchronization.
```

**Comment by viandoxdev** [comment]
So, is this done ?

**Comment by Benvii** [comment]
Still not working 😭, when a set a wrong date restart the raspberry pi (on an isolated network without internet), backend and ntp server started.
The date isn't updated 😔

A need a way to test the NTP server, do you have a cli for that ?

**Comment by viandoxdev** [comment]
`ntpdate -q 127.0.0.1` on the host

**Comment by viandoxdev** [comment]
But I'm pretty sure that the NTP server is working, what does `timedatectl status` and `$ timedatectl timesync-status` show ? Maybe the service just hasn't synced yet (It should do it every few minutes or so), but if that's the case then we need to find a way to force sync it.

**Comment by Benvii** [comment]
timesyncd doesn't work at all, it stays Idle I didn't find why, on the other hand ntp (client) was installed and running and didn't use our NTP server that's why the time was sync when you tested it, I have switch to ntp client and set our NTP server in it's configuration file.

Tested with ansible (SSH deploy), needs tests on a new fresh image.

**Comment by Benvii** [comment]
Still not working at first boot got :
```
(venv) pi@monkecar:~ $ sudo systemctl status ntp.service 
● ntp.service - Network Time Service
   Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-12-02 02:35:19 GMT; 6min ago
     Docs: man:ntpd(8)

Dec 02 02:34:35 monkecar systemd[1]: Starting Network Time Service...
Dec 02 02:34:42 monkecar root[648]: Got donkeycar manager ip: 192.168.20.107
Dec 02 02:35:19 monkecar config-ntp.sh[642]: Failed to set time zone: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)
Dec 02 02:35:19 monkecar systemd[1]: ntp.service: Control process exited, code=exited, status=1/FAILURE
Dec 02 02:35:19 monkecar systemd[1]: ntp.service: Failed with result 'exit-code'.
Dec 02 02:35:19 monkecar systemd[1]: Failed to start Network Time Service.
```

It works when doing a restart ... it going to be more complex than anticipated.

**Review by Benvii — CHANGES_REQUESTED** [review]
Not working at first boot.

**Comment by Benvii** [comment]
Maybe we can try : https://docs.ansible.com/ansible/latest/collections/community/general/timezone_module.html 

Or dig more about : systemd-firstboot

**Comment by viandoxdev** [comment]
Why does the time zone matter ? The error seems to be about it, so maybe just not setting it is an option (if we just use UTC)

**Comment by Benvii** [comment]
Well maybe we can do without it (if NTP takes care of the timezone .. I hope it does), but it's better to have the same timezone that the server, so that date command gives an understandable time without having to add/remove hours.
Timezone is certainly settable by Ansible, it shouldn't be too complex.

**Comment by viandoxdev** [comment]
Did it in ansible, build has been tested (only with the car-config role tho), `/etc/timezone` is correctly set so it should be ok.

**Review by Benvii — APPROVED** [review]
Finally, works at first boot thanks @viandoxdev

**Pull request merged**
