### PR TITLE
Create donkeycar part

### PR DESCRIPTION
**Pull request by viandoxdev**
This PR adds the donkeycar manager part (might rename later to not confuse with the donkeycar manager computer that will host the API)

### CODE REVIEW

**Comment by viandoxdev** [comment]
Thats not a good build error

**Comment by Benvii** [comment]
> Thats not a good build error

Some kind of registry issue for dependencies, I've re-started the build.

**Comment by viandoxdev** [comment]
I think this passes the checks, last error wasn't from me

**Comment by viandoxdev** [comment]
> > I think this passes the checks, last error wasn't from me
> 
> Reading the build log, in ansible recap you can see that there is a 1 failled, scroll up a bit and you see :
> 
> > Destination directory /home/py/mycar does not exist

Yea fixed that one, I managed to do the same typo twice and didn't fix them both in last commit. The build does occasionally fail because of random errors

**Comment by yannis-mlgrn** [comment]
@viandoxdev , issue fixed or already in resolving ?

**Comment by viandoxdev** [comment]
> @viandoxdev , issue fixed or already in resolving ?

Its an error on the apt upgrade, not something we can do anything about, restarting.

**Comment by Benvii** [comment]
I created a manager part with Job and worker, closing this PR.

**Pull request closed without merging**
