### PR TITLE
Fixes #63 Add custom joystick

### LINKED ISSUE #63: Being able to start/stop a record from the joystick controller and web
# Uses cases

Required uses cases :
- **UC1** As a donkeycar user/player I would like to be able to start and stop recording from the remote controller.
- **UC2** As a donkeycar administrator I would like to be able to start and stop recording from the web interface (and in the futur from a multi-car administration page).
-  **UC3** As a donkeycar administrator I would like to know from the web administration page if the recording is enabled or not (having it's current status accessible).

Optional uses cases : 
- **UC4** As a donkeycar user/player I would like a blinking LED on the controller when the recording is enabled, so that I know it's started.

# Implementation

We noticed that there is a PS4 controller type that might be used and already covers **UC1**, **UC2**  and **UC3**. But it doesn't control LED (**UC4**).

This issue is that the PS4 profile isn't correctly mapped and is not usable, but we can easily created our own joystick mapping / implementation using `donkeycar createjs` and would be able to re-create a working profile. Within this custom profile we would also be able to control the PS4 LED and try some blinking maybe.

This new PS4 fixed joystick implementation should then be pushed back to the donkeycar community.

### PR DESCRIPTION
**Pull request by viandoxdev**
Linked to #63

### CODE REVIEW

**Comment by viandoxdev** [comment]
Passing as draft as this needs a pretty bug rework:
We should keep a custom copy of manage.py (`templates/complete.py` on donkeycar repo), that subscribes a custom part that will serve as an interface between the API and whatever happens on the donkeycar server, and the cars themselves.
Maybe this should be moved to another PR, but this should also let us use run_conditions on the JoystickController part that **should** let us disable it to take controll with the webcontroller.

**Comment by Benvii** [comment]
Build tested on an other car with 2 joysticks, work perfectly at first boot. Recording state is well sync with controller LED.

**Comment by Benvii** [comment]
As branch needed rebase will need to be retested tomorrow  😢

**Review by Benvii — APPROVED** [review]
Image tested on real car it works well.

**Pull request merged**
