### PR TITLE
✨ Add donkeycar manager front

### PR DESCRIPTION
**Pull request by yannis-mlgrn**
- Fixes : #73 

# ✨ Features : 
- [x] F1
- [x] F2
- [x] F3
- [x] F4 
- [x] F5
- [x] F6 ( missing back ? , but a race is created when a car start running ?)
- [x] F7 ( missing back )
- [x] F8
- [x] F9
- [x] F10 ( missing back )
- [x] F11

**[see manager feature README ](https://github.com/mdl29/donkeycarLPH/blob/main/doc/donkeycarManager/manager-features.md)**

### CODE REVIEW

**Comment by yannis-mlgrn** [comment]
Front seem good but I can't finish it due to missing features

**Comment by yannis-mlgrn** [comment]
@Benvii  It's done

**Comment by yannis-mlgrn** [comment]
finish 🎉

**Comment by yannis-mlgrn** [comment]
`_vm.job1[0] is undefined` why `vm` . Do you have an idea @Benvii ??

**Comment by Benvii** [comment]
Some remarks : 

Fatal error : 
- [ ] Missing dependency : npm install --save vue-ins-progress-bar

Subscription :
- [ ]  for user subscription we need a big FAT pseudo input field clearly visible (from a color / contract) point of view, so that user can easily find it even if there is a lot of sun on the tablet .. big fields so that they can focus into it even with their fat fingers ^^
- [ ] after subscription, "ok button" in the modal as a strange position, should be centered (as it's the only button) and maybe bigger
- [ ] Why do I have 15min of waiting time, I'm the first player ? no one is in the queue .. we should remove it if the time is incorrect

Waiting board :
- [ ]   "éstimée" -> "Estimé"
- [ ]  display dates dynamically take a look at what we have done in scratchy

Dashboard : 

- [ ] For job ordering / ranking add and "up arrow" and "down arrow" to move up and down the job, logic behind these actions : 
     - move up arrow : when clicked, loop into the job list, always save "job_before" until you reach clicked job, use job_before to call "move_before_job" with clicked job to put before job_before


Still need to perform more test on Dashboard

**Comment by Benvii** [comment]
Register page :

- [ ]  modal "Ok" button still at a strange place and too small
- [ ]  can't register an existing player, we should be able to do so if someone wants to play again

dashboard :
- [ ]  Cars created doesn't show dynamically in the "cars" tab, is the event emitted ?
- [ ]  Cars > Settings : if clicked when no players and no job generate a lot of errors, see screenshot 
settingsWhenNoPlayersNoJob

- [ ] Cars : stopped cars are displayed, their worker status is STOPPED
- [ ]Cancel job fail see screenshot : 
cancelJobNotWorking



backend (so that we don't forget) :
- [ ] swagger rely on CDN, doesn't work on isolated network
- [ ] postman doesn't work in isolated network

**Review by Benvii — APPROVED** [review]

**Pull request merged**
