### PR TITLE
:sparkles: [Car + Back] End races

### PR DESCRIPTION
**Pull request by Benvii**
Add end_datetime into races.
As there are no events on races I'm not sure it will be useful ? Should I add races (updates) events @viandoxdev ?

### CODE REVIEW

**Comment by Benvii** [comment]
@viandoxdev do you have something to do in the frontend to handle this new field ?

**Comment by viandoxdev** [comment]
> @viandoxdev do you have something to do in the frontend to handle this new field ?

Yes, but I've already got a list of things to add I think I'm going to have everything in one or two PRs

**Comment by Benvii** [comment]
Hi @viandoxdev sorry I didn't reply to your question no update event on races I will add it today before merging this PR.

**Comment by Benvii** [comment]
Added events : `race.all.updated` and `race.$RACE_ID.updated` feel free to use them @viandoxdev

**Pull request merged**
