### PR TITLE
:sparkles: Jobs and Workers in API

### PR DESCRIPTION
**Pull request by Benvii**
WIP

### CODE REVIEW

**Comment by yannis-mlgrn** [comment]
# **Little review :**
missing `pyyaml` in python requirements 
- error : 
  ```
   File "/home/yannis/Documents/pro/donkeycarLPH/backend/donkeycarmanager/main.py", line 3, in <module>
      from donkeycarmanager.helpers.logging import setup_logging
    File "/home/yannis/Documents/pro/donkeycarLPH/backend/donkeycarmanager/helpers/logging.py", line 25, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
  ```

**Comment by Benvii** [comment]
Tyhanks @yannis-mlgrn fixed here [efbb924](https://github.com/mdl29/donkeycarLPH/pull/117/commits/efbb924927d6e83723feaf2cf328929395ea8c79)

**Comment by Benvii** [comment]
Todo :

- [ ] need de degraded behavior when no API is available on the network
- [ ] need a better wait to know which job is running currently on the car
- [ ] current_player ... on car objects aren't set

Hope I will be able to finish one day this PR 🥵

**Comment by Benvii** [comment]
To find the current job running we can GET `/jobs/?by_rank=true&skip=0&limit=100&worker_id=1&job_states=RUNNING&job_states=PAUSING&job_states=PAUSED&job_states=RESUMING&job_states=CANCELLING`

I don't know if its the best approach but it works.

**Comment by Benvii** [comment]
QA, found error at startup with ZeroConf :
```
Dec 02 02:47:46 bluecar python[847]: INFO:donkeycar.vehicle:Adding part MyJoystickController.
Dec 02 02:47:46 bluecar python[847]: DEBUG:custom.manager.car_manager.type:Trying to find API using zeroconf, remaining try : 15
Dec 02 02:47:49 bluecar python[847]: DEBUG:custom.manager.car_manager.type:Trying to find API using zeroconf, remaining try : 14
Dec 02 02:47:49 bluecar python[847]: ________             ______                   _________
Dec 02 02:47:49 bluecar python[847]: ___  __ \_______________  /___________  __    __  ____/_____ ________
Dec 02 02:47:49 bluecar python[847]: __  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
Dec 02 02:47:49 bluecar python[847]: _  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /
Dec 02 02:47:49 bluecar python[847]: /_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/
Dec 02 02:47:49 bluecar python[847]:                                  /____/
Dec 02 02:47:49 bluecar python[847]: using donkey v4.3.17 ...
Dec 02 02:47:49 bluecar python[847]: Starting Donkey Server...... you can now go to bluecar.local:8887 to drive your car.
Dec 02 02:47:49 bluecar python[847]: Traceback (most recent call last):
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/mycar/manage.py", line 876, in <module>
Dec 02 02:47:49 bluecar python[847]:     meta=args['--meta'])
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/mycar/manage.py", line 252, in drive
Dec 02 02:47:49 bluecar python[847]:     manager = CarManager(network_interface=rpi_network_interface)
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/mycar/custom/manager/car_manager.py", line 35, in __init__
Dec 02 02:47:49 bluecar python[847]:     self._api_origin = api_origin if api_origin else self._find_api_with_zero_conf()
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/mycar/custom/manager/car_manager.py", line 76, in _find_api_with_zero_conf
Dec 02 02:47:49 bluecar python[847]:     service = zeroconf.get_service_info(ZERO_CONF_TYPE, f"_{ZERO_CONF_NAME}.{ZERO_CONF_TYPE}")
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/venv/lib/python3.7/site-packages/zeroconf/_core.py", line 540, in get_service_info
Dec 02 02:47:49 bluecar python[847]:     if info.request(self, timeout, question_type):
Dec 02 02:47:49 bluecar python[847]:   File "/home/pi/venv/lib/python3.7/site-packages/zeroconf/_services/info.py", line 459, in request
Dec 02 02:47:49 bluecar python[847]:     assert zc.loop is not None and zc.loop.is_running()
Dec 02 02:47:49 bluecar python[847]: AssertionError
Dec 02 02:47:49 bluecar systemd[1]: donkeycar.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 02:47:49 bluecar systemd[1]: donkeycar.service: Failed with result 'exit-code'.
Dec 02 02:47:49 bluecar systemd[1]: donkeycar.service: Service RestartSec=100ms expired, scheduling restart.
Dec 02 02:47:49 bluecar systemd[1]: donkeycar.service: Scheduled restart job, restart counter is at 10.

```

Works if the API is started, need a fix.

**Pull request merged**
