### PR TITLE
Update jsfw version and add doc

### PR DESCRIPTION
**Pull request by viandoxdev**

### CODE REVIEW

**Comment by Benvii** [comment]
I tested it, the controller LED color is always green (#00ff00).

I have added logs on the car, LED color is correctly written into jsfw fifo : 
```
Feb 11 23:08:51 monkecar python[2890]: DEBUG:my_joystick:my_controller.py:write_to_controller with color_hex "#FF0000"
Feb 11 23:08:51 monkecar python[2890]: DEBUG:my_joystick:{"index": 0, "led_color": "#FF0000", "flash": [0, 0]}
Feb 11 23:08:51 monkecar python[2890]: INFO:donkeycar.parts.controller:Opening %s... /dev/input/js0
Feb 11 23:08:51 monkecar python[2890]: INFO:donkeycar.parts.controller:Device name: JSFW Virtual Device
Feb 11 23:08:51 monkecar python[2890]: DEBUG:my_joystick:my_controller.py:write_to_controller with color_hex "#FF0000"
Feb 11 23:08:51 monkecar python[2890]: DEBUG:my_joystick:{"index": 0, "led_color": "#FF0000", "flash": [0, 0]}
```

Meanwhile on the JSFW server side it displays (green color: #00ff00) : 
```
HID:     Forgetting device 'Sony Computer Entertainment Wireless Controller' (811105c4054c0003)
HID:     New device, Sony Computer Entertainment Wireless Controller [ctr] (event31: 811105c4054c0003)
CONN(0): [0] Found suitable [ctr] device: 'Sony Computer Entertainment Wireless Controller' (811105c4054c0003)
CONN(0):  Got message: 
HID:     (811105c4054c0003) Controller state: #00ff00 flash: (0, 0) rumble: (0, 0)
CONN(0):  Got message: 
HID:     (811105c4054c0003) Controller state: #00ff00 flash: (0, 0) rumble: (0, 0)
CONN(0):  Got message: 
HID:     (811105c4054c0003) Controller state: #00ff00 flash: (0, 0) rumble: (0, 0)
```

@viandoxdev can you take a look at it ?

**Review by Benvii — CHANGES_REQUESTED** [review]
Wrong LED color displayed. See PR comment for details.

**Comment by viandoxdev** [comment]
> Wrong LED color displayed. See PR comment for details.

Should be fixed, hopefully.

**Review by Benvii — APPROVED** [review]
Tested on real cars, LED bug fixed.

**Pull request merged**
